"""Report generation — HTML export for calculation results."""

def product_report_html(title: str, params: dict, metrics: list[tuple],
                         reserves: list = None, formula: str = "") -> str:
    """Generate a self-contained HTML report for a product calculation."""
    params_html = "".join(
        f"<tr><td><strong>{k}</strong></td><td>{v}</td></tr>"
        for k, v in params.items()
    )
    metrics_html = "".join(
        f"""<div style="flex:1;min-width:120px;background:#f9f9fb;border-radius:8px;
        padding:12px 16px;margin:6px;text-align:center">
        <div style="font-size:10px;color:#86868b;text-transform:uppercase;letter-spacing:0.05em">{label}</div>
        <div style="font-size:18px;font-weight:700;color:#1d1d1f;margin-top:4px">{value}</div>
        </div>"""
        for label, value in metrics
    )

    reserve_html = ""
    if reserves:
        rows = "".join(
            f"<tr><td>{i}</td><td style='text-align:right'>{float(r[1]) if isinstance(r, (tuple, list)) else float(r):,.2f}</td></tr>"
            for i, r in enumerate(reserves[:15])
        )
        reserve_html = f"""
        <h3>Reserve Table (first 15 years)</h3>
        <table><thead><tr><th>Year</th><th>Reserve</th></tr></thead><tbody>{rows}</tbody></table>
        """

    return f"""<!DOCTYPE html>
<html lang="zh">
<head><meta charset="UTF-8"><title>{title}</title>
<style>
body {{ font-family: -apple-system, "PingFang SC", sans-serif; max-width:700px; margin:40px auto; padding:0 20px; color:#1d1d1f; }}
h1 {{ font-size:22px; }} h2 {{ font-size:16px; margin-top:24px; color:#555; }}
.metrics {{ display:flex; flex-wrap:wrap; margin:16px 0; }}
table {{ width:100%; border-collapse:collapse; margin:12px 0; }}
th, td {{ padding:6px 12px; text-align:left; border-bottom:0.5px solid #e5e5ea; font-size:13px; }}
th {{ background:#f5f5f7; font-size:11px; text-transform:uppercase; color:#86868b; }}
.footer {{ margin-top:32px; font-size:11px; color:#aeaeb2; }}
</style></head>
<body>
<h1>{title}</h1>
<p style="color:#86868b">Generated by Life Insurance Actuarial Calculator</p>

<h2>Parameters</h2>
<table>{params_html}</table>

<h2>Results</h2>
<div class="metrics">{metrics_html}</div>
{reserve_html}

<p class="footer">github.com/chunchiulin2-crypto/life-insurance-calculator · For reference only</p>
</body></html>"""
